package com.dobyllm.packly.ui.theme

import androidx.compose.ui.graphics.Color

// Vibrant Minimalism brand palette from docs/ux/**/vibrant_minimalism/DESIGN.md.
val PacklySurface = Color(0xFFF8F9FA)
val PacklySurfaceDim = Color(0xFFD9DADB)
val PacklySurfaceBright = Color(0xFFF8F9FA)
val PacklySurfaceContainerLowest = Color(0xFFFFFFFF)
val PacklySurfaceContainerLow = Color(0xFFF3F4F5)
val PacklySurfaceContainer = Color(0xFFEDEEEF)
val PacklySurfaceContainerHigh = Color(0xFFE7E8E9)
val PacklySurfaceContainerHighest = Color(0xFFE1E3E4)
val PacklyOnSurface = Color(0xFF191C1D)
val PacklyOnSurfaceVariant = Color(0xFF3B4A44)
val PacklyInverseSurface = Color(0xFF2E3132)
val PacklyInverseOnSurface = Color(0xFFF0F1F2)
val PacklyOutline = Color(0xFF6B7B74)
val PacklyOutlineVariant = Color(0xFFB9CAC3)
val PacklySurfaceTint = Color(0xFF006B57)
val PacklyPrimary = Color(0xFF006B57)
val PacklyOnPrimary = Color(0xFFFFFFFF)
val PacklyPrimaryContainer = Color(0xFF00E5BC)
val PacklyOnPrimaryContainer = Color(0xFF00614F)
val PacklyInversePrimary = Color(0xFF00E0B8)
val PacklySecondary = Color(0xFF6844C7)
val PacklyOnSecondary = Color(0xFFFFFFFF)
val PacklySecondaryContainer = Color(0xFF9C7AFE)
val PacklyOnSecondaryContainer = Color(0xFF310082)
val PacklyTertiary = Color(0xFF006591)
val PacklyOnTertiary = Color(0xFFFFFFFF)
val PacklyTertiaryContainer = Color(0xFF94D2FF)
val PacklyOnTertiaryContainer = Color(0xFF005B84)
val PacklyError = Color(0xFFBA1A1A)
val PacklyOnError = Color(0xFFFFFFFF)
val PacklyErrorContainer = Color(0xFFFFDAD6)
val PacklyOnErrorContainer = Color(0xFF93000A)
val PacklyPrimaryFixed = Color(0xFF42FDD3)
val PacklyPrimaryFixedDim = Color(0xFF00E0B8)
val PacklyOnPrimaryFixed = Color(0xFF002019)
val PacklyOnPrimaryFixedVariant = Color(0xFF005141)
val PacklySecondaryFixed = Color(0xFFE8DDFF)
val PacklySecondaryFixedDim = Color(0xFFCEBDFF)
val PacklyOnSecondaryFixed = Color(0xFF21005E)
val PacklyOnSecondaryFixedVariant = Color(0xFF5028AE)
val PacklyTertiaryFixed = Color(0xFFC9E6FF)
val PacklyTertiaryFixedDim = Color(0xFF89CEFF)
val PacklyOnTertiaryFixed = Color(0xFF001E2F)
val PacklyOnTertiaryFixedVariant = Color(0xFF004C6E)
val PacklyBackground = Color(0xFFF8F9FA)
val PacklyOnBackground = Color(0xFF191C1D)
val PacklySurfaceVariant = Color(0xFFE1E3E4)
